<script src="{{asset('user_assets/js/jquery.min.js')}}"></script>
  <script src="{{asset('user_assets/js/jquery-migrate-3.0.1.min.js')}}"></script>
  <script src="{{asset('user_assets/js/popper.min.js')}}"></script>
  <script src="{{asset('user_assets/js/bootstrap.min.js')}}"></script>
  <script src="{{asset('user_assets/js/jquery.easing.1.3.js')}}"></script>
  <script src="{{asset('user_assets/js/jquery.waypoints.min.js')}}"></script>
  <script src="{{asset('user_assets/js/jquery.stellar.min.js')}}"></script>
  <script src="{{asset('user_assets/js/owl.carousel.min.js')}}"></script>
  <script src="{{asset('user_assets/js/jquery.magnific-popup.min.js')}}"></script>
  <script src="{{asset('user_assets/js/aos.js')}}"></script>
  <script src="{{asset('user_assets/js/jquery.animateNumber.min.js')}}"></script>
  <script src="{{asset('user_assets/js/bootstrap-datepicker.js')}}"></script>
  <script src="{{asset('user_assets/js/jquery.timepicker.min.js')}}"></script>
  <script src="{{asset('user_assets/js/scrollax.min.js')}}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{{asset('user_assets/js/google-map.js')}}"></script>
  <script src="{{asset('user_assets/js/main.js')}}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>    
  